# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import git_pb2 as git__pb2


class GitStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAndInitDirectory = channel.unary_unary(
        '/git.Git/CreateAndInitDirectory',
        request_serializer=git__pb2.Request_Path.SerializeToString,
        response_deserializer=git__pb2.Response_Result.FromString,
        )
    self.AddOrUpdateFile = channel.unary_unary(
        '/git.Git/AddOrUpdateFile',
        request_serializer=git__pb2.Request_File.SerializeToString,
        response_deserializer=git__pb2.Response_Result.FromString,
        )


class GitServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateAndInitDirectory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddOrUpdateFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GitServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAndInitDirectory': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAndInitDirectory,
          request_deserializer=git__pb2.Request_Path.FromString,
          response_serializer=git__pb2.Response_Result.SerializeToString,
      ),
      'AddOrUpdateFile': grpc.unary_unary_rpc_method_handler(
          servicer.AddOrUpdateFile,
          request_deserializer=git__pb2.Request_File.FromString,
          response_serializer=git__pb2.Response_Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'git.Git', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
